### ISSUE TITLE
Compatibility with most recent version of GPflow

### ISSUE THREAD

**Issue by JIMonroe** [usnistgov/thermoextrap#2]
GPflow is now on version 2.9.0 and we pin to less than 2.6.0.  I need to assess if there are any breaking changes, then upgrade.  Additionally, there may now be some better ways to implement some of the GP models.

**Comment by JIMonroe** [comment]
I have a pull request to fix this that's pretty much good to go.  It was actually pretty easy, and would have just "worked" with a GPflow update, but I tried to do the right thing and also update to the new style for likelihoods (they take the input data, X, as an argument now).  That ended up changing how it makes sense to initialize the main likelihood class (`HetGaussianDeriv`).  It's a breaking change, but tests are all passing after making adjustments and I believe all of the example code should still run just fine.

Only one thing I need from @wpk-nist-gov...  After changing the pyproject.toml file so GPflow is unrestricted, how do I re-build all of the files in the environment directory?  Something with pyproject2conda, I'm sure, but from looking through the documentation there I could only see how to do a single file at a time.

**Comment by JIMonroe** [comment]
@wpk-nist-gov, see the pull request above.  I did try to run `pyproject2conda` with `nox` (via `make environment-files-build`) but ran into a ModuleNotFoundError (for `tools`) during the import of `tools.noxtools`.  It doesn't look like there's an `__init__.py` in the `tools` directory, so I'm not sure it's importable?  I left this for an additional commit since I was confused why it should have been working before or when it got broken.

**Comment by JIMonroe** [comment]
Actually, when we update the environment files, we should actually set `gpflow>=2.6.0` in `pyproject.toml`.  There were some breaking changes to fit the likelihood style past 2.6.0, as well as some potentially breaking imports for the mean function class.

**Comment by wpk-nist-gov** [comment]
I'm not sure why you got that error for importing `tools.noxtools`.  It works on my end without a file`tools/__init__.py`.  Maybe something with python version behind nox?  I'm really not sure. You can try to add the file `tools/__init__.py` and see if that fixes it.  If so, I'll add that file to the repo.

**Comment by JIMonroe** [comment]
Just tried adding `__init__.py` and it made no difference (apparently it's not strictly necessary after python 3.3).  What's strange is that if I just fire up a python prompt and try importing, it works fine.  It's only when I try and use nox.

**Comment by wpk-nist-gov** [comment]
OK.  I think I might know what the problem is.  The noxfile looks for a config file `.noxconfig.toml`.  This file specifies some user specific stuff.  To use virtualenvs alongside conda envs, you need access to python interpreters across versions.  [Here](https://pages.nist.gov/thermoextrap/contributing.html#notes-on-nox) is the documentation for setting that up.  But there's also an option for setting up optional extras in the different created environment files.  I realized just now that if `.noxconfig.toml` doesn't exist, then everything breaks.  So I fixed the `noxfile.py` to still work even if this file doesn't exist.  To test, you can do something like the following to setup an isolated nox env.  First update develop branch.

```bash
$ conda create -n bootstrap-nox python=3.10 nox ruamel.yaml
$ conda activate bootstrap-nox
$ pip install noxopt
$ nox -s pyproject2conda
```

If you still have issues, run the following as well:

```bash
$ for version in 3.8 3.9 3.10 3.11; do
    conda create -n test-${version} python=${version}
  done
```

And create a file `.noxconfig.toml` in the root of the repo:

```toml
[nox.python]
paths = ["~/.conda/envs/test-3.*/bin"]

# Extras for environments
# for example, could have
# dev = ["dev", "nox", "tools"]
[nox.extras]
dev = ["dev", "nox"]
```

where `~/.conda/envs/` should be replaced with whatever your prefix to conda envs is.

This may seem convoluted, but it lets me use a mix of virtual env types.  The classic python virtualenv's are super fast to build and lightweight.  But for testing, I still use conda environments.  I tried to just use [pyenv](https://github.com/pyenv/pyenv), but it didn't play nice with my workflow.

**Comment by JIMonroe** [comment]
Well, I saw the commits to develop updating gpflow, etc., so I am closing this issue.

I tried all the above after pulling the latest commits to develop, but the nox stuff still is not working for me, which means it's probably an issue on my end.  Wouldn't worry about this too much, but if you want we can start a new issue for that so we don't get too off-track in this thread.
